name: Release CI

on:
  push:
    tags:
      - 'v*'

jobs:
  build-stage:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ windows-latest, macos-latest, ubuntu-latest ]

    steps:
      - name: check out code
        uses: actions/checkout@v3

      - name: Install dependencies
        uses: actions/setup-node@v3
      - run: npm install

      - name: build the app
        run: npm run build:electron

      - uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: release/*_*.{exe,dmg,AppImage}
          retention-days: 3

  release-stage:
    needs: build-stage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v2
        with:
          name: artifacts
          path: artifacts
      - name: Create Release
        uses: softprops/action-gh-release@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ env.version }}
          name: Gostx v${{ env.version }}
          body: See the assets to download this version and install.
          prerelease: false
          generate_release_notes: false
          files: 'artifacts/**'