name: 构建 Electron 应用程序

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: 构建和发布 Electron 应用程序

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [windows-2019, macos-10.15, ubuntu-18.04]

    steps:
      - name: 检出代码库
        uses: actions/checkout@v3

      - name: 安装 Node.js
        uses: actions/setup-node@v3

      - name: 安装依赖
        run: npm install

      - name: 构建应用程序
        run: npm run build:electron

      - name: 移动构建产物到 artifacts 目录
        run: |
          mkdir -p artifacts
          if ($env:os -eq "windows-2019" -and (Get-ChildItem release -Filter "*.exe" -Recurse)) {
            mv release/**/*.exe artifacts
          } elseif ($env:os -eq "macos-10.15" -and (Get-ChildItem release -Filter "*.dmg" -Recurse)) {
            mv release/**/*.dmg artifacts
          } elseif ($env:os -eq "ubuntu-18.04" -and (Get-ChildItem release -Filter "*.AppImage" -Recurse)) {
            mv release/**/*.AppImage artifacts
          } else {
            Write-Host "未找到 $env:os 的构建产物"
          }

      - name: 显示 artifacts 目录内容
        run: ls artifacts

      - name: 上传构建产物
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.os }}
          path: artifacts

      - name: 创建 Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: 'artifacts/**'
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}